---
- name: Get latest version of tomcat 7
  shell: ls -d -r "{{ tcserver_install_dir }}/tomcat-7"* | head -1 | sed -e 's/^.*tomcat-//'
  register: tomcat_7_latest_version
  # Don't report this as changed
  changed_when: no

- name: Get latest version of tomcat 8
  shell: ls -d -r "{{ tcserver_install_dir }}/tomcat-8"* | head -1 | sed -e 's/^.*tomcat-//'
  register: tomcat_8_latest_version
  # Don't report this as changed
  changed_when: no

- name: Set tomcat_latest_versions
  set_fact:
    # Create a new dictionary with the provided items
    # http://stackoverflow.com/a/35608380/399105
    tomcat_latest_versions: "{{ tomcat_latest_versions | default({}) | combine({item.major_version: item.specific_version}) }}"
  with_items:
    - { major_version: 7, specific_version: "{{ tomcat_7_latest_version.stdout }}" }
    - { major_version: 8, specific_version: "{{ tomcat_8_latest_version.stdout }}" }
